import {
  Activity,
  Apple,
  Award,
  Banknote,
  Bike,
  BookOpen,
  Briefcase,
  Building,
  Bus,
  Calculator,
  Calendar,
  Camera,
  Car,
  Clock,
  Code,
  Coffee,
  Coins,
  CreditCard,
  DollarSign,
  Dumbbell,
  Film,
  Flame,
  Fuel,
  Gamepad2,
  Gift,
  Globe,
  GraduationCap,
  Hammer,
  Headphones,
  Heart,
  HeartPulse,
  Home,
  Key,
  Laptop,
  Leaf,
  Library,
  Lightbulb,
  type LucideIcon,
  Mail,
  MoreHorizontal,
  Monitor,
  Music,
  Package,
  PawPrint,
  Phone,
  Pill,
  PiggyBank,
  Pizza,
  Plane,
  Popcorn,
  Receipt,
  Repeat,
  Scissors,
  School,
  Shirt,
  ShoppingBag,
  ShoppingBasket,
  ShoppingCart,
  Smartphone,
  Sofa,
  Sparkles,
  Star,
  Stethoscope,
  Sun,
  Tag,
  Thermometer,
  Ticket,
  Train,
  TrendingUp,
  Trophy,
  Truck,
  Tv,
  Users,
  Wallet,
  Wifi,
  Wine,
  Wrench,
  Zap,
} from "lucide-react";

export type IconSection = {
  label: string;
  icons: string[];
};

export const CATEGORY_ICON_SECTIONS: IconSection[] = [
  {
    label: "Finanças & Dinheiro",
    icons: ["Banknote", "Wallet", "CreditCard", "PiggyBank", "TrendingUp", "DollarSign", "Receipt", "Coins"],
  },
  {
    label: "Alimentação & Bebidas",
    icons: ["UtensilsCrossed", "Coffee", "Pizza", "Apple", "Wine", "ShoppingBasket", "Flame"],
  },
  {
    label: "Transporte",
    icons: ["Car", "Bus", "Train", "Bike", "Plane", "Truck", "Fuel"],
  },
  {
    label: "Moradia & Casa",
    icons: ["Home", "Sofa", "Wrench", "Hammer", "Key", "Lightbulb", "Wifi", "Zap"],
  },
  {
    label: "Saúde & Bem-estar",
    icons: ["HeartPulse", "Heart", "Stethoscope", "Pill", "Activity", "Dumbbell", "Thermometer"],
  },
  {
    label: "Educação",
    icons: ["GraduationCap", "BookOpen", "Library", "School", "Calculator", "Award"],
  },
  {
    label: "Lazer & Entretenimento",
    icons: ["Popcorn", "Music", "Gamepad2", "Camera", "Tv", "Film", "Trophy", "Ticket"],
  },
  {
    label: "Compras",
    icons: ["ShoppingBag", "ShoppingCart", "Package", "Tag", "Gift", "Star", "Shirt"],
  },
  {
    label: "Tecnologia",
    icons: ["Smartphone", "Laptop", "Monitor", "Headphones", "Globe", "Code"],
  },
  {
    label: "Trabalho & Negócios",
    icons: ["Briefcase", "Building", "Users", "Clock", "Calendar", "Mail", "Phone"],
  },
  {
    label: "Outros",
    icons: ["Repeat", "Sparkles", "PawPrint", "Leaf", "Sun", "Scissors", "MoreHorizontal"],
  },
];

const ICON_MAP: Record<string, LucideIcon> = {
  Activity,
  Apple,
  Award,
  Banknote,
  Bike,
  BookOpen,
  Briefcase,
  Building,
  Bus,
  Calculator,
  Calendar,
  Camera,
  Car,
  Clock,
  Code,
  Coffee,
  Coins,
  CreditCard,
  DollarSign,
  Dumbbell,
  Film,
  Flame,
  Fuel,
  Gamepad2,
  Gift,
  Globe,
  GraduationCap,
  Hammer,
  Headphones,
  Heart,
  HeartPulse,
  Home,
  Key,
  Laptop,
  Leaf,
  Library,
  Lightbulb,
  Mail,
  Monitor,
  MoreHorizontal,
  Music,
  Package,
  PawPrint,
  Phone,
  Pill,
  PiggyBank,
  Pizza,
  Plane,
  Popcorn,
  Receipt,
  Repeat,
  Scissors,
  School,
  Shirt,
  ShoppingBag,
  ShoppingBasket,
  ShoppingCart,
  Smartphone,
  Sofa,
  Sparkles,
  Star,
  Stethoscope,
  Sun,
  Tag,
  Thermometer,
  Ticket,
  Train,
  TrendingUp,
  Trophy,
  Truck,
  Tv,
  Users,
  Wallet,
  Wifi,
  Wine,
  Wrench,
  Zap,
};

export const CATEGORY_ICONS: Record<string, LucideIcon> = ICON_MAP;

export const CATEGORY_ICON_NAMES = CATEGORY_ICON_SECTIONS.flatMap((s) => s.icons);

export function getCategoryIcon(name: string): LucideIcon {
  return ICON_MAP[name] ?? Wallet;
}
